[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "SmallBlueClient"
version = "0.1.1"
description = "Community BigBlueButton automation client"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{name = "SmallBlueClient community"}]
dependencies = ["websocket-client>=1.7", "livekit>=1.1,<2", "av>=14,<18", "aiortc>=1.15,<2", "websockets>=13,<14"]

[project.optional-dependencies]
docs = ["sphinx>=8,<9", "furo>=2024.8.6", "myst-parser>=4,<5", "linkify-it-py>=2,<3"]

[project.urls]
Homepage = "https://github.com/BolinoIR/SmallBlueClient/"
Documentation = "https://sbc.protobuf.lol"

[tool.setuptools.packages.find]
include = ["sbc*"]

[tool.setuptools.package-data]
sbc = ["py.typed", "*.md"]
"sbc.operations" = ["*.pyi"]
